# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
metrics_address=http://127.0.0.1:8082
grpc_inference_address=127.0.0.1
grpc_management_address=127.0.0.1
grpc_inference_port=17070
grpc_management_port=17071
model_store=./model-store
load_models=all
